version: '3.3'
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    hostname: mariadb
    env_file:
      - .env
    build: ./requirements/mariadb/
    volumes:
      - 'db-vol:/var/lib/mysql'
    networks:
      - inception-network
    restart: always
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - '-uroot'
        - '-p${DB_ROOT_PASS}'
        - ping
        - '--silent'
      timeout: 10s
      retries: 3
  adminer:
    container_name: adminer
    image: adminer
    hostname: adminer
    depends_on:
      - mariadb
    build: ./requirements/bonus/adminer
    ports:
      - '8080:80'
    restart: on-failure
    networks:
      - inception-network
  nginx:
    container_name: nginx
    image: nginx
    hostname: nginx
    depends_on:
      - wordpress
    environment:
      - 'DOMAIN_NAME=${DOMAIN_NAME}'
    build: ./requirements/nginx
    volumes:
      - 'wp-vol:/var/www/html'
    ports:
      - '443:443'
    restart: on-failure
    networks:
      - inception-network
  wordpress:
    container_name: wordpress
    image: wordpress
    hostname: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
    build: ./requirements/wordpress
    volumes:
      - 'wp-vol:/var/www/html'
    networks:
      - inception-network
    restart: on-failure
    healthcheck:
      test:
        - CMD
        - curl
        - '-fk'
        - 'https://nginx'
      interval: 30s
      timeout: 10s
      retries: 3
  ftp:
    container_name: ftp
    image: ftp
    hostname: ftp
    env_file:
      - .env
    depends_on:
      - wordpress
    build: ./requirements/bonus/ftp
    volumes:
      - 'wp-vol:/home/${FTP_USER}/ftp/'
    restart: on-failure
    ports:
      - '20:20'
      - '21:21'
      - '40000-40005:40000-40005'
    networks:
      - inception-network
  redis:
    container_name: redis
    image: redis
    hostname: redis
    build: ./requirements/bonus/redis
    restart: on-failure
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      timeout: 10s
      retries: 3
    networks:
      - inception-network
  static:
    container_name: static
    image: static
    hostname: static
    restart: on-failure
    ports:
      - '5555:80'
    build: ./requirements/bonus/static
  cadvisor:
    container_name: cadvisor
    image: cadvisor
    hostname: cadvisor
    restart: on-failure
    build: ./requirements/bonus/cadvisor
    privileged: true
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:ro'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/dev/disk/:/dev/disk:ro'
    ports:
      - '9999:8080'
    networks:
      - inception-network
volumes:
  db-vol:
    driver_opts:
      type: 'none'
      o: bind
      device: '${DB_DATA_PATH}'
  wp-vol:
    driver_opts:
      type: 'none'
      o: bind
      device: '${WP_DATA_PATH}'
networks:
  inception-network: