version: '3'
services:
  db:
    build: ./requirements/mariadb/
    restart: always
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - wpsite

  adminer:
    depends_on:
      - db
    build: ./requirements/bonus/adminer
    restart: always
    ports:
      - '8080:80'
    networks:
      - wpsite

  nginx:
    build: ./requirements/nginx
    restart: always
    ports:
      - '443:443'
      - '8000:8000'
    networks:
      - wpsite

volumes:
  db-vol:
    driver_opts:
      type: 'none'
      o: bind
      device: /Users/$USER/data/db-data
networks:
  wpsite:
