version: '3.3'

services:
  mariadb:
    env_file:
      - .env
    build: ./requirements/mariadb/
    restart: on-failure
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - inception-network

  adminer:
    depends_on:
      - mariadb
    build: ./requirements/bonus/adminer
    restart: always
    ports:
      - '8080:80'
    networks:
      - inception-network

  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    restart: on-failure
    volumes:
      - wp-vol:/var/www/html
    ports:
      - '443:443'
    networks:
      - inception-network

  wordpress:
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - mariadb
      - redis
    build: ./requirements/wordpress
    volumes:
      - wp-vol:/var/www/html
    networks:
      - inception-network

  ftp:
    restart: on-failure
    depends_on:
      - wordpress
    build: ./requirements/bonus/ftp
    volumes:
      - wp-vol:/home/xxx/ftp/
    ports:
      - '20:20'
      - '21:21'
      - '40000-40005:40000-40005'
    networks:
      - inception-network

  redis:
    restart: on-failure
    build: ./requirements/bonus/redis
    networks:
      - inception-network

  static:
    restart: on-failure
    ports:
      - 5555:80
    build: ./requirements/bonus/static
  
  cadvisor:
    build: ./requirements/bonus/cadvisor
    volumes:
      - /:/rootfs:ro 
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro 
      - /dev/disk/:/dev/disk:ro 
    ports:
      - 9999:8080
    networks:
      - inception-network

volumes:
  db-vol:
    driver_opts:
      type: 'none'
      o: bind
      device: /Users/$USER/data/db-data
  wp-vol:
    driver_opts:
      type: 'none'
      o: bind
      device: /Users/$USER/data/wp-data

networks:
  inception-network:
    driver: bridge
