version: '3.3'
services:
  mariadb:
    env_file:
      - .env
    build: ./requirements/mariadb/
    restart: on-failure
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - wpsite

  adminer:
    depends_on:
      - mariadb
    build: ./requirements/bonus/adminer
    restart: always
    ports:
      - '8080:80'
    networks:
      - wpsite

  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    restart: on-failure
    volumes:
      - wp-vol:/var/www/html
    ports:
      - '443:443'
    networks:
      - wpsite

  wordpress:
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - mariadb
      - redis
    build: ./requirements/wordpress
    volumes:
      - wp-vol:/var/www/html
    networks:
      - wpsite

  ftp:
    restart: on-failure
    depends_on:
      - wordpress
    build: ./requirements/bonus/ftp
    volumes:
      - wp-vol:/home/xxx/ftp/
    ports:
      - '20:20'
      - '21:21'
      - '40000-40005:40000-40005'
    networks:
      - wpsite

  redis:
    restart: on-failure
    # depends_on:
    #   - wordpress
    build: ./requirements/bonus/redis
    # volumes:
    #   - wp-vol:/home/xxx/ftp/
    # ports:
    #   - 6379:6379
      # - '20:20'
      # - '21:21'
      # - '40000-40005:40000-40005'
    networks:
      - wpsite

volumes:
  db-vol:
    driver_opts:
      type: 'none'
      o: bind
      device: /Users/$USER/data/db-data
  wp-vol:
    driver_opts:
      type: 'none'
      o: bind
      device: /Users/$USER/data/wp-data

networks:
  wpsite:
    driver: bridge
