version: '3'
services:
  db:
    build: ./requirements/mariadb/
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wpsite

  adminer:
    depends_on:
      - db
    build: ./requirements/bonus/adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      - wpsite

  nginx:
    build: ./requirements/nginx
    restart: always
    ports:
      - '443:443'
      - '8000:8000'
    networks:
      - wpsite

volumes:
  db_data:
networks:
  wpsite:
